version: '3.8'

services:
  db:
    image: "postgres:9.6-alpine"
    container_name: "postgresqldb"
    volumes: 
      - postgresql-data:/var/lib/postgresql/data
    ports:
      - "5000:5432"
    environment:      
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=teste12
      - POSTGRES_DB=crudGenerico

  app:
    image: teste-deliver-it
    ports:
      - "8082:8082"
    build: 
      context: ./
      dockerfile: Dockerfile
    environment: 
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/crudGenerico
    depends_on:
      - db

volumes: 
  postgresql-data:
