version: '3.8'

services:
  db:
    image: "postgres:9.6-alpine"
    container_name: "postgresqldb"
    volumes: 
      - postgresql-data:/var/lib/postgresql/data
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql

    ports:
      - "5000:5432"
    environment:      
      - POSTGRES_DB=contabilidade
      - POSTGRES_USER=gerente
      - POSTGRES_PASSWORD=teste12

  app:
    image: app
    container_name: app_deliverIT
    ports:
      - "8082:8082"
    build: 
      context: ./
      dockerfile: Dockerfile
    environment: 
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/contabilidade
    depends_on:
      - db

volumes: 
  postgresql-data:
